# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "server" => ["default"]
    }
    ansible.verbose = "vv"
    ansible.extra_vars = {
      default_user: "vagrant"
    }

    ansible.playbook = "playbook.yml"
  end
end
