# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.13.37"

  config.vm.synced_folder "../../", "/bentham"

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
        "server" => ["default"]
      }
    ansible.verbose = "v"
    ansible.extra_vars = {
      default_user: "vagrant",
    }

    ansible.playbook = "ansible/deploy.yml"
  end
end
