- name: rabbitmq | install rabbitmq
  apt: name=rabbitmq-server

- name: rabbitmq | start service
  service:
    name: rabbitmq-server
    state: started

- name: rabbitmq | add user
  rabbitmq_user:
    user: rabbit
    password: rabbit
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: rabbitmq | remove default guest user
  rabbitmq_user:
    user: guest
    state: absent
