datastore:
  type:     postgres
  database: bentham
  host:     192.168.13.37
  user:     bentham
  password: bentham

authentication:
  personal_github:
    username: your_user_name
    access_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

trackers:
  - name:     github_notifications
    task:     bentham.trackers.github.notifications
    authentication: personal_github
    interval: 30
