- name: create service account for celery
  user: name=celery
        system=yes
        home=/var/lib/celery
        shell=/bin/false
        state=present

- name: install celery
  pip:
    name: "celery"
    state: present
