- name: create service account for celery
  user:
    name: celery
    system: yes
    home: /var/lib/celery
    shell: /bin/bash
    state: present

- name: install celery
  pip:
    name: "celery"
    state: present

- name: copy celery and celery beat daemon scripts
  template:
    src: "{{ item }}.j2"
    dest: "/etc/init.d/{{ item }}"
    mode: 0755
  with_items:
    - celeryd
    - celerybeat

- name: copy celery and celery beat defaults scripts
  template:
    src: "{{ item }}.defaults.j2"
    dest: "/etc/default/{{ item }}"
    mode: 0755
  with_items:
    - celeryd
    - celerybeat
  notify:
    - restart celeryd
