- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: add database
  sudo_user: postgres
  postgresql_db:
    name=bentham

- name: add hstore extension
  sudo_user: postgres
  postgresql_ext:
    name=hstore
    db=bentham

- name: add bentham user
  sudo_user: postgres
  postgresql_user:
    db=bentham
    name=bentham
    password=bentham
    role_attr_flags=SUPERUSER

- name: listen on all addresses
  lineinfile:
    dest=/etc/postgresql/9.3/main/postgresql.conf
    regexp=^listen_addresses
    line="listen_addresses = '*'"

- name: listen locally (IPv4)
  lineinfile:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line='host    all             all             127.0.0.1/32            md5'
    state=absent
- name: listen locally (IPv4)
  lineinfile:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    line='host    all             all             0.0.0.0/0            md5'
    insertafter='^# IPv4 local connections:'
    state=present
  notify: restart postgresql

- name: create schema
  sudo_user: postgres
  shell:
    "psql bentham -f /bentham/devops/ansible/roles/postgres/files/schema.sql"

- name: create triggers
  sudo_user: postgres
  shell:
    "psql bentham -f /bentham/devops/ansible/roles/postgres/files/triggers.sql"
