- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: add database
  sudo_user: postgres
  postgresql_db:
    name=bentham

- name: add hstore extension
  sudo_user: postgres
  postgresql_ext:
    name=hstore
    db=bentham

- name: add bentham user
  sudo_user: postgres
  postgresql_user:
    db=bentham
    name=bentham
    password=bentham
    priv=ALL

- name: listen on all addresses
  lineinfile:
    dest=/etc/postgresql/9.3/main/postgresql.conf
    regexp=^listen_addresses
    line="listen_addresses = '*'"

- name: allow md5 authentication
  replace:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    regexp='peer$'
    replace='md5'

- name: allow local connections from 0.0.0.0/0
  replace:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    regexp='127\.0\.0\.1\/32'
    replace='0.0.0.0/0'
  notify: restart postgresql
